# Generated by Django 2.0.5 on 2018-05-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swahilipot', '0002_auto_20180523_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
