# Generated by Django 2.0.5 on 2018-05-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('national_id', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('biography', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=20)),
                ('dob', models.DateTimeField(verbose_name='date of birth')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
